version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:5.2.0
    container_name: kibana
    environment:
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: changeme
      ELASTICSEARCH_URL: http://elasticsearch1:9200
    ports:
      - 5601:5601
    networks:
      - esnet

networks:
  esnet:
    driver: bridge
